//! Raw FFI bindings to libmodsecurity (ModSecurity v3)
//!
//! These bindings are manually defined to avoid the build-time complexity of bindgen.
//! They cover the essential ModSecurity C API functions needed for WAF scanning.
//!
//! # Safety
//!
//! All functions in this module are `unsafe` and require careful handling of:
//! - Raw pointers (null checks, lifetime management)
//! - Memory allocation/deallocation (caller must cleanup)
//! - Thread safety (ModSecurity engine is NOT thread-safe)
//!
//! # Reference
//!
//! Based on libmodsecurity v3 headers:
//! - <https://github.com/SpiderLabs/ModSecurity/blob/v3/master/headers/modsecurity/modsecurity.h>
//! - <https://github.com/SpiderLabs/ModSecurity/blob/v3/master/headers/modsecurity/rules_set.h>
//! - <https://github.com/SpiderLabs/ModSecurity/blob/v3/master/headers/modsecurity/transaction.h>
//! - <https://github.com/SpiderLabs/ModSecurity/blob/v3/master/headers/modsecurity/intervention.h>

use std::os::raw::{c_char, c_int, c_uchar, c_void};

/// Opaque ModSecurity engine handle
#[repr(C)]
pub struct ModSecurity {
    _private: [u8; 0],
}

/// Opaque RulesSet handle
#[repr(C)]
pub struct RulesSet {
    _private: [u8; 0],
}

/// Opaque Transaction handle
#[repr(C)]
pub struct Transaction {
    _private: [u8; 0],
}

/// ModSecurity intervention structure
///
/// When a rule triggers a disruptive action, this structure is populated
/// with the action to take.
#[repr(C)]
#[derive(Debug)]
pub struct ModSecurityIntervention {
    /// HTTP status code to return (0 = no intervention)
    pub status: c_int,
    /// Whether intervention should pause processing
    pub pause: c_int,
    /// Redirect URL (if status is 3xx)
    pub url: *mut c_char,
    /// Log message
    pub log: *mut c_char,
    /// Whether the intervention is disruptive
    pub disruptive: c_int,
}

impl Default for ModSecurityIntervention {
    fn default() -> Self {
        Self {
            // Initialize status to 200 (not 0) as required by libmodsecurity
            // See: https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v3.x)#msc_intervention
            status: 200,
            pause: 0,
            url: std::ptr::null_mut(),
            log: std::ptr::null_mut(),
            disruptive: 0,
        }
    }
}

// Link directives are emitted by build.rs (static linking)
extern "C" {
    // =========================================================================
    // Core ModSecurity Engine Functions
    // =========================================================================

    /// Initialize the ModSecurity engine
    ///
    /// Returns a pointer to the engine, or NULL on failure.
    /// Must be cleaned up with `msc_cleanup`.
    pub fn msc_init() -> *mut ModSecurity;

    /// Set connector information string
    ///
    /// This identifies the connector (e.g., "api_fence/1.0") in logs.
    pub fn msc_set_connector_info(msc: *mut ModSecurity, connector: *const c_char);

    /// Set the log callback function
    ///
    /// The callback is called for each log message generated by ModSecurity.
    /// The callback receives user data and a pointer to the log message string.
    ///
    /// # Arguments
    /// - `msc`: ModSecurity engine handle
    /// - `cb`: Callback function with signature: fn(*mut c_void, *const c_void)
    ///   First arg is user data, second is the log message (const char*)
    pub fn msc_set_log_cb(
        msc: *mut ModSecurity,
        cb: Option<unsafe extern "C" fn(*mut c_void, *const c_void)>,
    );

    /// Clean up and free the ModSecurity engine
    ///
    /// # Safety
    /// - `msc` must be a valid pointer from `msc_init`
    /// - Must not be called while transactions are in progress
    pub fn msc_cleanup(msc: *mut ModSecurity);

    // =========================================================================
    // Rules Set Functions
    // =========================================================================

    /// Create a new rules set
    ///
    /// Returns a pointer to the rules set, or NULL on failure.
    /// Must be cleaned up with `msc_rules_cleanup`.
    pub fn msc_create_rules_set() -> *mut RulesSet;

    /// Add rules from a file
    ///
    /// # Arguments
    /// - `rules`: Rules set handle
    /// - `file`: Path to the rules file (null-terminated)
    /// - `error`: Pointer to store error message (caller must free)
    ///
    /// # Returns
    /// Number of rules loaded, or negative on error
    pub fn msc_rules_add_file(
        rules: *mut RulesSet,
        file: *const c_char,
        error: *mut *const c_char,
    ) -> c_int;

    /// Add rules from a remote URL
    ///
    /// # Arguments
    /// - `rules`: Rules set handle
    /// - `key`: API key for authentication (can be NULL)
    /// - `uri`: URL to fetch rules from
    /// - `error`: Pointer to store error message (caller must free)
    ///
    /// # Returns
    /// Number of rules loaded, or negative on error
    pub fn msc_rules_add_remote(
        rules: *mut RulesSet,
        key: *const c_char,
        uri: *const c_char,
        error: *mut *const c_char,
    ) -> c_int;

    /// Add rules from a string
    ///
    /// # Arguments
    /// - `rules`: Rules set handle
    /// - `plain_rules`: ModSecurity rules as a string
    /// - `error`: Pointer to store error message (caller must free)
    ///
    /// # Returns
    /// Number of rules loaded, or negative on error
    pub fn msc_rules_add(
        rules: *mut RulesSet,
        plain_rules: *const c_char,
        error: *mut *const c_char,
    ) -> c_int;

    /// Clean up and free a rules set
    pub fn msc_rules_cleanup(rules: *mut RulesSet);

    // =========================================================================
    // Transaction Functions
    // =========================================================================

    /// Create a new transaction
    ///
    /// # Arguments
    /// - `msc`: ModSecurity engine handle
    /// - `rules`: Rules set to use for this transaction
    /// - `log_callback`: Optional callback for logging (can be NULL)
    ///
    /// # Returns
    /// Pointer to transaction, or NULL on failure
    pub fn msc_new_transaction(
        msc: *mut ModSecurity,
        rules: *mut RulesSet,
        log_callback: *mut c_void,
    ) -> *mut Transaction;

    /// Process connection information
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `client_ip`: Client IP address
    /// - `client_port`: Client port
    /// - `server_ip`: Server IP address
    /// - `server_port`: Server port
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_connection(
        transaction: *mut Transaction,
        client_ip: *const c_char,
        client_port: c_int,
        server_ip: *const c_char,
        server_port: c_int,
    ) -> c_int;

    /// Process URI and method
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `uri`: Request URI
    /// - `method`: HTTP method
    /// - `http_version`: HTTP version string (e.g., "1.1", "2.0")
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_uri(
        transaction: *mut Transaction,
        uri: *const c_char,
        method: *const c_char,
        http_version: *const c_char,
    ) -> c_int;

    /// Add a request header (with explicit lengths)
    ///
    /// NOTE: We use the `_n` variant which takes explicit lengths instead of
    /// null-terminated strings. This is safer for Rust strings which are not
    /// null-terminated.
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `key`: Header name
    /// - `key_len`: Length of header name
    /// - `value`: Header value
    /// - `value_len`: Length of header value
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    #[link_name = "msc_add_n_request_header"]
    pub fn msc_add_request_header(
        transaction: *mut Transaction,
        key: *const c_uchar,
        key_len: usize,
        value: *const c_uchar,
        value_len: usize,
    ) -> c_int;

    /// Process all request headers (call after adding all headers)
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_request_headers(transaction: *mut Transaction) -> c_int;

    /// Append request body data
    ///
    /// Can be called multiple times to append chunks.
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `body`: Body data
    /// - `size`: Size of body data
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_append_request_body(
        transaction: *mut Transaction,
        body: *const c_uchar,
        size: usize,
    ) -> c_int;

    /// Process the complete request body
    ///
    /// Call after all body data has been appended.
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_request_body(transaction: *mut Transaction) -> c_int;

    /// Add a response header (with explicit lengths)
    ///
    /// NOTE: We use the `_n` variant which takes explicit lengths instead of
    /// null-terminated strings. This is safer for Rust strings which are not
    /// null-terminated.
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `key`: Header name
    /// - `key_len`: Length of header name
    /// - `value`: Header value
    /// - `value_len`: Length of header value
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    #[link_name = "msc_add_n_response_header"]
    pub fn msc_add_response_header(
        transaction: *mut Transaction,
        key: *const c_uchar,
        key_len: usize,
        value: *const c_uchar,
        value_len: usize,
    ) -> c_int;

    /// Process response headers
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `status`: HTTP response status code
    /// - `protocol`: Protocol string (e.g., "1.1", "2.0")
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_response_headers(
        transaction: *mut Transaction,
        status: c_int,
        protocol: *const c_char,
    ) -> c_int;

    /// Append response body data
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `body`: Body data
    /// - `size`: Size of body data
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_append_response_body(
        transaction: *mut Transaction,
        body: *const c_uchar,
        size: usize,
    ) -> c_int;

    /// Process the complete response body
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_response_body(transaction: *mut Transaction) -> c_int;

    /// Process logging phase
    ///
    /// Call at the end of the transaction to finalize logging.
    ///
    /// # Returns
    /// 1 on success, 0 on failure
    pub fn msc_process_logging(transaction: *mut Transaction) -> c_int;

    /// Check for intervention
    ///
    /// Checks if any rule triggered a disruptive action.
    ///
    /// # Arguments
    /// - `transaction`: Transaction handle
    /// - `intervention`: Pointer to intervention struct to populate
    ///
    /// # Returns
    /// 1 if intervention required, 0 if not
    pub fn msc_intervention(
        transaction: *mut Transaction,
        intervention: *mut ModSecurityIntervention,
    ) -> c_int;

    /// Clean up and free a transaction
    pub fn msc_transaction_cleanup(transaction: *mut Transaction);
}

#[cfg(test)]
mod tests {
    // Tests require libmodsecurity to be installed
    // Run with: cargo test --features modsecurity-tests

    #[test]
    #[ignore = "requires libmodsecurity installed"]
    fn test_ffi_init_cleanup() {
        unsafe {
            let modsec = super::msc_init();
            assert!(!modsec.is_null());
            super::msc_cleanup(modsec);
        }
    }
}
